// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ621D1RFPoOVAe7kSYaVPyT5nnujF3iU',
    appId: '1:321843783524:web:62ef6926eb5b2648667c71',
    messagingSenderId: '321843783524',
    projectId: 'reusedepot-f7394',
    authDomain: 'reusedepot-f7394.firebaseapp.com',
    storageBucket: 'reusedepot-f7394.firebasestorage.app',
    measurementId: 'G-2VC1SWVHY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkPtqmgZb5Hup9O_3loeAtJkHFGhNDpls',
    appId: '1:321843783524:android:680fb2c586465d8c667c71',
    messagingSenderId: '321843783524',
    projectId: 'reusedepot-f7394',
    storageBucket: 'reusedepot-f7394.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Ec-GVk9wTdjDxliTNLM_gXgq2tNSEqg',
    appId: '1:321843783524:ios:ed4aff1352d3dea8667c71',
    messagingSenderId: '321843783524',
    projectId: 'reusedepot-f7394',
    storageBucket: 'reusedepot-f7394.firebasestorage.app',
    iosBundleId: 'com.example.reuseDepot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Ec-GVk9wTdjDxliTNLM_gXgq2tNSEqg',
    appId: '1:321843783524:ios:ed4aff1352d3dea8667c71',
    messagingSenderId: '321843783524',
    projectId: 'reusedepot-f7394',
    storageBucket: 'reusedepot-f7394.firebasestorage.app',
    iosBundleId: 'com.example.reuseDepot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ621D1RFPoOVAe7kSYaVPyT5nnujF3iU',
    appId: '1:321843783524:web:6b901bd4c1d40806667c71',
    messagingSenderId: '321843783524',
    projectId: 'reusedepot-f7394',
    authDomain: 'reusedepot-f7394.firebaseapp.com',
    storageBucket: 'reusedepot-f7394.firebasestorage.app',
    measurementId: 'G-8QL06KX6HP',
  );
}
